/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jehian
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mdivisi = new javax.swing.JCheckBoxMenuItem();
        mout1 = new javax.swing.JCheckBoxMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mjabatan = new javax.swing.JCheckBoxMenuItem();
        mout2 = new javax.swing.JCheckBoxMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mpegawai = new javax.swing.JCheckBoxMenuItem();
        mout3 = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Divisi");

        mdivisi.setSelected(true);
        mdivisi.setText("Form Divisi");
        mdivisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mdivisiActionPerformed(evt);
            }
        });
        jMenu1.add(mdivisi);

        mout1.setSelected(true);
        mout1.setText("CLOSE");
        mout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mout1ActionPerformed(evt);
            }
        });
        jMenu1.add(mout1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Jabatan");

        mjabatan.setSelected(true);
        mjabatan.setText("Form Jabatan");
        mjabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mjabatanActionPerformed(evt);
            }
        });
        jMenu2.add(mjabatan);

        mout2.setSelected(true);
        mout2.setText("CLOSE");
        mout2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mout2ActionPerformed(evt);
            }
        });
        jMenu2.add(mout2);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Pegawai");

        mpegawai.setSelected(true);
        mpegawai.setText("Form Pegawai");
        mpegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpegawaiActionPerformed(evt);
            }
        });
        jMenu3.add(mpegawai);

        mout3.setSelected(true);
        mout3.setText("CLOSE");
        mout3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mout3ActionPerformed(evt);
            }
        });
        jMenu3.add(mout3);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mpegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpegawaiActionPerformed
        new pegawai().setVisible(true);
    }//GEN-LAST:event_mpegawaiActionPerformed

    private void mdivisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mdivisiActionPerformed
        new divisi().setVisible(true);
    }//GEN-LAST:event_mdivisiActionPerformed

    private void mjabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mjabatanActionPerformed
        new jabatan().setVisible(true);
    }//GEN-LAST:event_mjabatanActionPerformed

    private void mout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mout1ActionPerformed
        dispose();
        new login().setVisible(true);
    }//GEN-LAST:event_mout1ActionPerformed

    private void mout2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mout2ActionPerformed
        dispose();
        new login().setVisible(true);
    }//GEN-LAST:event_mout2ActionPerformed

    private void mout3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mout3ActionPerformed
        dispose();
        new login().setVisible(true);
    }//GEN-LAST:event_mout3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JCheckBoxMenuItem mdivisi;
    private javax.swing.JCheckBoxMenuItem mjabatan;
    private javax.swing.JCheckBoxMenuItem mout1;
    private javax.swing.JCheckBoxMenuItem mout2;
    private javax.swing.JCheckBoxMenuItem mout3;
    private javax.swing.JCheckBoxMenuItem mpegawai;
    // End of variables declaration//GEN-END:variables
}
